name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Executa o workflow em pushes para a branch 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Define o ambiente onde o workflow será executado

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Faz o checkout do código-fonte do repositório

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Define a versão do Node.js a ser usada
      with:
        node-version: '18'  # Atualize para a versão Node.js 18 ou superior

    - name: Install dependencies
      run: npm install  # Instala as dependências definidas no package.json

    - name: Build
      run: npm run build  # Executa o comando de build, se necessário para o seu projeto

    - name: Deploy to Firebase Hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}  # Usa o token de acesso pessoal para Firebase CLI
      run: |
        npm install -g firebase-tools  # Instala o Firebase CLI globalmente
        firebase deploy --only hosting  # Faz o deploy para o Firebase Hosting
